import os

BOX_NAME = os.getenv("BOX_NAME")
BLOB_STORAGE_URL = os.getenv("BLOB_STORAGE_URL")
BLOB_STORAGE_ACCESS_KEY = os.getenv("BLOB_STORAGE_ACCESS_KEY")
BLOB_STORAGE_SECRET_KEY = os.getenv("BLOB_STORAGE_SECRET_KEY")

BLOB_STORAGE_BUCKET = os.getenv("BLOB_STORAGE_BUCKET")
BLOB_STORAGE_PATH = os.getenv("BLOB_STORAGE_PATH")

MQTT_BROKER_URL = os.getenv("MQTT_BROKER_URL")
MQTT_BROKER_USERNAME = os.getenv("MQTT_BROKER_USERNAME")
MQTT_BROKER_PASSWORD = os.getenv("MQTT_BROKER_PASSWORD")
MQTT_TOPIC = os.getenv("MQTT_TOPIC")

print("BOX_NAME:", BOX_NAME)
print("BLOB_STORAGE_URL:", BLOB_STORAGE_URL)
print("BLOB_STORAGE_ACCESS_KEY:", BLOB_STORAGE_ACCESS_KEY)
print("BLOB_STORAGE_SECRET_KEY:", BLOB_STORAGE_SECRET_KEY)
print("BLOB_STORAGE_BUCKET:", BLOB_STORAGE_BUCKET)
print("BLOB_STORAGE_PATH:", BLOB_STORAGE_PATH)
print("MQTT_BROKER_URL:", MQTT_BROKER_URL)
print("MQTT_BROKER_USERNAME:", MQTT_BROKER_USERNAME)
print("MQTT_BROKER_PASSWORD:", MQTT_BROKER_PASSWORD)
print("MQTT_TOPIC:", MQTT_TOPIC)

environment_variables = os.environ
print("\nAll varaibles\n")
for key, value in environment_variables.items():
    print(f"{key}: {value}")